name: check2
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ktlint:
    name: Check 2
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone PR
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Ktlint
        uses: lucasnlm/ktlint-action@master
